version: '3'
services:
  psql:
    image: postgres:latest
    container_name: psql
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      - POSTGRES_DB=otp_code_db
      - POSTGRES_USER=postgre_user
      - POSTGRES_PASSWORD=postgre_secret_password
    volumes:
      - database_data:/var/lib/postgresql/data/


volumes:
  database_data: